// 5 AM i coudlnt think but want to finish so this one generated by AI, Duck im cooked
"use client"

import { useState, useEffect } from "react"

export function useResponsiveLimit() {
  const [limit, setLimit] = useState(4)

  useEffect(() => {
    const updateLimit = () => {
      if (window.innerWidth >= 1024) {
        // Desktop: show 8 cards
        setLimit(8)
      } else if (window.innerWidth >= 642) {
        // Mobile/Tablet: show 4 cards
        setLimit(4)
      } else {
        // Mobile/Tablet: show 4 cards
        setLimit(3)
      } 
    }

    // Set initial limit
    updateLimit()

    // Add event listener for window resize
    window.addEventListener("resize", updateLimit)

    // Cleanup
    return () => window.removeEventListener("resize", updateLimit)
  }, [])

  return limit
}
